version: '2'

services:
  web:
    build: .
    links:
      - db
    ports:
      - '8000:5000'
    networks:
      - default

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: akhil
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: crud
    networks:
      - default