#DB Secret File
apiVersion: v1
kind: Secret
metadata:
  name: flaskcrud-secrets
type: Opaque
data:
  db_root_password: cm9vdA== 
  db_name: Y3J1ZA== 
  db_access_user: YWtoaWw=  
  db_access_password: cGFzc3dvcmQ= 
  