# My SQL Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: flask-pv-storage
        persistentVolumeClaim:
          claimName: flask-pv-claim
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskcrud-secrets
              key: db_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: flaskcrud-secrets
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flaskcrud-secrets
              key: db_access_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskcrud-secrets
              key: db_access_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: flask-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: db
  type: ClusterIP